from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 595)
        MainWindow.setStyleSheet("background-color: rgb(208, 255, 254);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(-5, 0, 1031, 141))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(50)
        self.Title.setFont(font)
        self.Title.setStyleSheet("background-color: rgb(25, 120, 200);")
        self.Title.setObjectName("Title")
        self.register_2 = QtWidgets.QPushButton(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(630, 250, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(30)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.register_2.setObjectName("register_2")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(120, 200, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.email.setFont(font)
        self.email.setAutoFillBackground(False)
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email.setText("")
        self.email.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email.setObjectName("email")
        self.register_3 = QtWidgets.QPushButton(self.centralwidget)
        self.register_3.setGeometry(QtCore.QRect(630, 380, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(30)
        self.register_3.setFont(font)
        self.register_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.register_3.setObjectName("register_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 160, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 290, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 420, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.email_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.email_2.setGeometry(QtCore.QRect(120, 460, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.email_2.setFont(font)
        self.email_2.setAutoFillBackground(False)
        self.email_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_2.setText("")
        self.email_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email_2.setObjectName("email_2")
        self.email_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.email_3.setGeometry(QtCore.QRect(120, 330, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.email_3.setFont(font)
        self.email_3.setAutoFillBackground(False)
        self.email_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_3.setText("")
        self.email_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email_3.setObjectName("email_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#000000;\">AniTrack</span></p></body></html>"))
        self.register_2.setText(_translate("MainWindow", "Register"))
        self.register_3.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Email"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Verify Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
